### ISSUE TITLE
chrome support

### ISSUE THREAD

**Issue by nekolr** [evilpie/404-bookmarks#15]
Thanks to the author for developing this extension. I made a few modifications based on this repo to support the chrome browser.

see: <https://github.com/nekolr/404-bookmarks>

**Comment by evilpie** [comment]
Thanks for reaching out. If you want I could merge some of those changes like `s/browser/chrome/`

**Comment by nekolr** [comment]
> 
> 
> Thanks for reaching out. If you want I could merge some of those changes like `s/browser/chrome/`

My pleasure, what should I do, the changes I made on the chrome branch

**Comment by evilpie** [comment]
Sure.
- I mean these changes where you use "chrome.xyz" instead of "browser.xyz": https://github.com/nekolr/404-bookmarks/commit/29aa41f1993ae6c7794954adf39eb3efa212abcb#diff-f9b12bd72f40c9b8ed144484f0f12a5fL5
- I see you added some Chinese comments in certain undocumented places, translated to English adding those would probably be a good idea as well.
- I think we still need https://github.com/nekolr/404-bookmarks/commit/29aa41f1993ae6c7794954adf39eb3efa212abcb#diff-9a9569e9d73f33740eada95275da7f30L5-L26 otherwise you get a lot of wrong results in Firefox.

So if you want you can open a PR with just those first two items, otherwise feel free to just ignore this. I am not actively working on this extension at the moment anyway.

**Comment by nekolr** [comment]
> 
> 
> Sure.
> 
>     * I mean these changes where you use "chrome.xyz" instead of "browser.xyz": [nekolr@29aa41f#diff-f9b12bd72f40c9b8ed144484f0f12a5fL5](https://github.com/nekolr/404-bookmarks/commit/29aa41f1993ae6c7794954adf39eb3efa212abcb#diff-f9b12bd72f40c9b8ed144484f0f12a5fL5)
> 
>     * I see you added some Chinese comments in certain undocumented places, translated to English adding those would probably be a good idea as well.
> 
>     * I think we still need [nekolr@29aa41f#diff-9a9569e9d73f33740eada95275da7f30L5-L26](https://github.com/nekolr/404-bookmarks/commit/29aa41f1993ae6c7794954adf39eb3efa212abcb#diff-9a9569e9d73f33740eada95275da7f30L5-L26) otherwise you get a lot of wrong results in Firefox.
> 
> 
> So if you want you can open a PR with just those first two items, otherwise feel free to just ignore this. I am not actively working on this extension at the moment anyway.

I mean maybe we can open another branch and then I submit a pr to this branch?
yeah, i will clear chinese comments.

**Comment by evilpie** [comment]
Sounds about right. Create a new branch in your fork with just those changes and then open a pull request.

**Comment by nekolr** [comment]
![Snipaste_2020-04-08_08-48-59.png](https://i.loli.net/2020/04/08/Oh5Tgt8pYR7lSUj.png)

Maybe you can create a new branch, and i will submit a pr to that branch?
